name: JOY挂机

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */6 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【JOY挂机】"
              run: |
                  node jd_crazy_joy_coin.js
              env:
                  JD_COOKIE: pt_key=AAJgMPeWADBvUGxu4ARuepZWNn8GyztVce8Rl48HoZarzgzb4_Aa4rW3mtvHAfAdpp9Z41v4VUg;pt_pin=%E5%91%A8%E9%BD%90%E5%86%9B;
